#!/bin/sh

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

export this_file=${0}
export this_dir=`dirname ${this_file}`
source $this_dir/env

export this_script_path=`dirname $0`
cd ${this_script_path}

source ${GIMEL_HOME}/build/gimel_functions

cd ${GIMEL_HOME}/gimel-dataapi/gimel-standalone/docker
write_log "Current Directory is --> ${PWD}"
run_cmd "docker-compose stop -t 90"
write_log "SUCCESS !!!"
